/**
 * Long-form legal copy lives together so factual changes to cookies, storage,
 * analytics and subprocessors can be reviewed across every language at once.
 * Locale dictionaries still own the page titles and headings.
 */
export const legalContent = {
	en: {
		cookiePolicy: `<p><strong class="text-text-primary">Last updated:</strong> September 9, 2026.</p>
<p>RANKMAKER uses only first-party cookies that are necessary for sign-in, account security and the mature-content preference. We do not use advertising or third-party analytics cookies.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. Cookies We Use</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Cookie</th><th class="px-4 py-3 border-b border-border">Purpose</th><th class="px-4 py-3 border-b border-border">Duration</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">Keeps you signed in and identifies your server-side session.</td><td class="px-4 py-3">30 days</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">Secures the Google or GitHub sign-in redirect and returns you to the requested page.</td><td class="px-4 py-3">10 minutes</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">Temporarily carries the verified sign-in details needed to finish creating an account.</td><td class="px-4 py-3">15 minutes</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">Remembers whether you chose to display templates marked as mature.</td><td class="px-4 py-3">1 year</td></tr></tbody></table></div><p class="mt-4">These cookies are set by RANKMAKER, use SameSite=Lax and are not used for advertising. The authentication cookies are HTTP-only, so browser scripts cannot read them.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. Browser Storage</h2><p>We use local storage to keep guest-created templates, ranking history, ranking progress and interface caches on your device. Session storage is used for short-lived form and navigation handoffs. This lets guest features work without an account. Clearing site data removes these local copies; content saved to an account remains on our servers until you delete it or your account.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. Analytics</h2><p>We use Cloudflare Web Analytics for aggregate visits, page views and performance measurements. Its browser beacon does not set cookies. Cloudflare states that Web Analytics does not collect or use visitors' personal data. Product actions such as starting a ranking are also counted by RANKMAKER's own server so public usage totals and product metrics work without third-party analytics.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. Your Controls</h2><p>You can block or delete cookies and browser storage from your browser settings. Blocking the necessary cookies may prevent sign-in, account creation or the mature-content preference from working. Because we do not set optional cookies, RANKMAKER does not show a cookie-consent banner.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. Changes and Contact</h2><p>We may update this policy when the technologies used by the Service change. For questions, email <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">Last updated:</strong> September 9, 2026.</p>
<p>This Privacy Policy explains how RANKMAKER collects and uses information when you use rankmaker.net and its services (the "Service").</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. Information We Collect</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Account information:</strong> your username, chosen avatar, a stable identifier from the sign-in provider you select, and your email address and its verification status when the provider supplies them.</li><li><strong class="text-text-primary">Content and activity:</strong> templates, images, comments, votes, follows, saved templates, ranking results, preferences and notification choices that you submit or save.</li><li><strong class="text-text-primary">Product measurements:</strong> events such as starting a ranking, the template involved, date, coarse country and, when signed in, your account identifier. Guest-template measurements contain an opaque local identifier and milestone timestamps, not the template's title, options or images.</li><li><strong class="text-text-primary">Technical information:</strong> network and device information processed by our infrastructure providers to deliver and secure the Service.</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. How We Use Information</h2><ul class="list-disc pl-5 space-y-2"><li>Provide accounts, rankings, templates and community features.</li><li>Secure the Service, prevent abuse and diagnose failures.</li><li>Maintain aggregate counts, understand product usage and improve performance.</li><li>Send activity notifications you have not disabled.</li></ul><p class="mt-3"><strong class="text-text-primary">Marketing emails.</strong> We send RANKMAKER news only when you explicitly opt in. This choice is off by default, separate from activity notifications and can be withdrawn at any time from Preferences.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Cookies, Local Storage and Analytics</h2><p>RANKMAKER uses necessary first-party cookies for authentication, OAuth security and the mature-content preference, plus browser storage for guest features and local history. We do not use advertising or third-party analytics cookies. Cloudflare Web Analytics provides aggregate traffic and performance measurements without setting cookies; Cloudflare states that it does not collect or use visitors' personal data.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. Service Providers and Disclosure</h2><p class="mb-3">We do not sell personal data and do not use it for third-party advertising. We use the following providers only as needed to operate the Service:</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare:</strong> hosting, security, database and object storage, image processing, AI-assisted descriptions and privacy-first web analytics.</li><li><strong class="text-text-primary">Google or GitHub:</strong> the provider you choose authenticates you and returns the account identifier and email details described above.</li><li><strong class="text-text-primary">Resend:</strong> delivery of notification or opt-in marketing emails.</li><li><strong class="text-text-primary">OpenAI:</strong> automated moderation of images you choose to upload, when moderation is enabled.</li></ul><p class="mt-3">We may also disclose information when required by law or necessary to protect users, the Service or our legal rights.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. Retention and Deletion</h2><p>We keep personal data only as long as needed to provide the Service, meet legal obligations and protect it from abuse. You can delete your account from your profile. This removes the account, its templates, uploaded images and saved ranking results. Comments are detached and shown as deleted-user content so other people's replies remain intact. Aggregate or de-identified product measurements may remain without an active account record.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. Your Rights</h2><p>Depending on where you live, you may have rights to access, correct, delete, restrict or object to processing of your personal data, receive a portable copy, or withdraw consent. We may need to verify your identity before completing a request. You may also complain to your local data-protection authority.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. Children</h2><p>The Service is not directed to children under 13, and we do not knowingly collect their personal information.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. Security and International Processing</h2><p>We use technical and organizational safeguards, but no internet service can guarantee absolute security. Our providers may process data in countries other than yours under their applicable safeguards.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. Changes and Contact</h2><p>We may update this policy when the Service changes. Material changes will be communicated through the Service or by email when appropriate. To exercise your rights or ask a question, email <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`
	},
	es: {
		cookiePolicy: `<p><strong class="text-text-primary">Última actualización:</strong> 9 de septiembre de 2026.</p>
<p>RANKMAKER utiliza únicamente cookies propias necesarias para iniciar sesión, proteger la cuenta y guardar la preferencia de contenido adulto. No utilizamos cookies publicitarias ni cookies analíticas de terceros.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. Cookies que utilizamos</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Cookie</th><th class="px-4 py-3 border-b border-border">Finalidad</th><th class="px-4 py-3 border-b border-border">Duración</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">Mantiene tu sesión iniciada e identifica la sesión en el servidor.</td><td class="px-4 py-3">30 días</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">Protege la redirección de inicio de sesión con Google o GitHub y permite volver a la página solicitada.</td><td class="px-4 py-3">10 minutos</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">Conserva temporalmente los datos verificados necesarios para terminar de crear una cuenta.</td><td class="px-4 py-3">15 minutos</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">Recuerda si has elegido mostrar plantillas marcadas como contenido adulto.</td><td class="px-4 py-3">1 año</td></tr></tbody></table></div><p class="mt-4">Estas cookies las establece RANKMAKER, utilizan SameSite=Lax y no se usan para publicidad. Las cookies de autenticación son HTTP-only, por lo que los scripts del navegador no pueden leerlas.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. Almacenamiento del navegador</h2><p>Utilizamos almacenamiento local para conservar en tu dispositivo las plantillas creadas como invitado, el historial y progreso de rankings y algunas cachés de interfaz. El almacenamiento de sesión se usa para formularios y transiciones temporales entre páginas. Al borrar los datos del sitio se eliminan estas copias locales; el contenido guardado en una cuenta permanece en nuestros servidores hasta que lo elimines o borres la cuenta.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. Analítica</h2><p>Utilizamos Cloudflare Web Analytics para obtener mediciones agregadas de visitas, páginas vistas y rendimiento. Su baliza del navegador no instala cookies. Cloudflare declara que Web Analytics no recopila ni utiliza datos personales de los visitantes. RANKMAKER también cuenta en sus propios servidores acciones de producto, como iniciar un ranking, para mantener los totales públicos y las métricas sin analítica de terceros.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. Tus controles</h2><p>Puedes bloquear o eliminar cookies y almacenamiento del navegador desde su configuración. Bloquear las cookies necesarias puede impedir que funcionen el inicio de sesión, la creación de cuentas o la preferencia de contenido adulto. Como no instalamos cookies opcionales, RANKMAKER no muestra un banner de consentimiento.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. Cambios y contacto</h2><p>Podemos actualizar esta política cuando cambien las tecnologías del Servicio. Para cualquier consulta, escribe a <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">Última actualización:</strong> 9 de septiembre de 2026.</p>
<p>Esta Política de Privacidad explica cómo RANKMAKER recopila y utiliza información cuando usas rankmaker.net y sus servicios (el «Servicio»).</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. Información que recopilamos</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Datos de cuenta:</strong> tu nombre de usuario, avatar elegido, un identificador estable del proveedor de acceso seleccionado y tu correo electrónico y su estado de verificación cuando el proveedor los facilita.</li><li><strong class="text-text-primary">Contenido y actividad:</strong> plantillas, imágenes, comentarios, votos, seguimientos, plantillas guardadas, resultados de rankings, preferencias y opciones de notificación que envías o guardas.</li><li><strong class="text-text-primary">Mediciones del producto:</strong> eventos como iniciar un ranking, la plantilla implicada, la fecha, el país aproximado y, si has iniciado sesión, el identificador de tu cuenta. Las mediciones de plantillas de invitado contienen un identificador local opaco y fechas de hitos, no el título, las opciones ni las imágenes de la plantilla.</li><li><strong class="text-text-primary">Información técnica:</strong> datos de red y dispositivo tratados por nuestros proveedores de infraestructura para prestar y proteger el Servicio.</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. Cómo utilizamos la información</h2><ul class="list-disc pl-5 space-y-2"><li>Proporcionar cuentas, rankings, plantillas y funciones comunitarias.</li><li>Proteger el Servicio, prevenir abusos y diagnosticar fallos.</li><li>Mantener recuentos agregados, entender el uso del producto y mejorar el rendimiento.</li><li>Enviar notificaciones de actividad que no hayas desactivado.</li></ul><p class="mt-3"><strong class="text-text-primary">Correos comerciales.</strong> Solo enviamos novedades de RANKMAKER si das tu consentimiento expreso. Esta opción está desactivada por defecto, es independiente de las notificaciones de actividad y puede retirarse en cualquier momento desde Preferencias.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Cookies, almacenamiento local y analítica</h2><p>RANKMAKER utiliza cookies propias necesarias para la autenticación, la seguridad OAuth y la preferencia de contenido adulto, además de almacenamiento del navegador para las funciones de invitado y el historial local. No utilizamos cookies publicitarias ni cookies analíticas de terceros. Cloudflare Web Analytics proporciona mediciones agregadas de tráfico y rendimiento sin instalar cookies; Cloudflare declara que no recopila ni utiliza datos personales de los visitantes.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. Proveedores y divulgación</h2><p class="mb-3">No vendemos datos personales ni los utilizamos para publicidad de terceros. Utilizamos los siguientes proveedores solo cuando son necesarios para operar el Servicio:</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare:</strong> alojamiento, seguridad, base de datos y almacenamiento de objetos, tratamiento de imágenes, descripciones asistidas por IA y analítica web centrada en la privacidad.</li><li><strong class="text-text-primary">Google o GitHub:</strong> el proveedor que elijas te autentica y devuelve el identificador de cuenta y los datos de correo descritos anteriormente.</li><li><strong class="text-text-primary">Resend:</strong> entrega de notificaciones y correos comerciales consentidos.</li><li><strong class="text-text-primary">OpenAI:</strong> moderación automatizada de las imágenes que decidas subir, cuando la moderación está habilitada.</li></ul><p class="mt-3">También podemos divulgar información cuando la ley lo exija o sea necesario para proteger a los usuarios, el Servicio o nuestros derechos legales.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. Conservación y eliminación</h2><p>Conservamos los datos personales solo durante el tiempo necesario para prestar el Servicio, cumplir obligaciones legales y protegerlo frente a abusos. Puedes eliminar tu cuenta desde tu perfil. Esto elimina la cuenta, sus plantillas, imágenes subidas y resultados guardados. Los comentarios se desvinculan y aparecen como contenido de un usuario eliminado para conservar las respuestas de otras personas. Las mediciones agregadas o desidentificadas pueden permanecer sin un registro de cuenta activo.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. Tus derechos</h2><p>Según tu lugar de residencia, puedes tener derecho a acceder, rectificar, suprimir, limitar u oponerte al tratamiento de tus datos personales, recibir una copia portable o retirar tu consentimiento. Es posible que debamos verificar tu identidad antes de atender una solicitud. También puedes reclamar ante tu autoridad de protección de datos.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. Menores</h2><p>El Servicio no está dirigido a menores de 13 años y no recopilamos conscientemente sus datos personales.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. Seguridad y tratamiento internacional</h2><p>Aplicamos medidas técnicas y organizativas, pero ningún servicio de Internet puede garantizar una seguridad absoluta. Nuestros proveedores pueden tratar datos en países distintos al tuyo conforme a las garantías que les resulten aplicables.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. Cambios y contacto</h2><p>Podemos actualizar esta política cuando cambie el Servicio. Comunicaremos los cambios relevantes a través del Servicio o por correo cuando corresponda. Para ejercer tus derechos o realizar una consulta, escribe a <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`
	},
	fr: {
		cookiePolicy: `<p><strong class="text-text-primary">Dernière mise à jour :</strong> 9 septembre 2026.</p>
<p>RANKMAKER utilise uniquement des cookies internes nécessaires à la connexion, à la sécurité du compte et à la préférence de contenu pour adultes. Nous n'utilisons aucun cookie publicitaire ou analytique tiers.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. Cookies utilisés</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Cookie</th><th class="px-4 py-3 border-b border-border">Finalité</th><th class="px-4 py-3 border-b border-border">Durée</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">Maintient votre connexion et identifie votre session côté serveur.</td><td class="px-4 py-3">30 jours</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">Sécurise la redirection de connexion Google ou GitHub et vous ramène à la page demandée.</td><td class="px-4 py-3">10 minutes</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">Transporte temporairement les informations vérifiées nécessaires pour terminer la création du compte.</td><td class="px-4 py-3">15 minutes</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">Mémorise votre choix d'afficher les modèles signalés comme contenu pour adultes.</td><td class="px-4 py-3">1 an</td></tr></tbody></table></div><p class="mt-4">Ces cookies sont définis par RANKMAKER, utilisent SameSite=Lax et ne servent pas à la publicité. Les cookies d'authentification sont HTTP-only et ne peuvent donc pas être lus par les scripts du navigateur.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. Stockage du navigateur</h2><p>Le stockage local conserve sur votre appareil les modèles créés en tant qu'invité, l'historique et la progression des classements ainsi que certains caches d'interface. Le stockage de session sert aux formulaires et transitions temporaires. Effacer les données du site supprime ces copies locales ; le contenu enregistré dans un compte reste sur nos serveurs jusqu'à sa suppression ou celle du compte.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. Analytique</h2><p>Cloudflare Web Analytics fournit des mesures agrégées des visites, pages vues et performances. Sa balise ne dépose aucun cookie. Cloudflare déclare que Web Analytics ne collecte ni n'utilise les données personnelles des visiteurs. RANKMAKER compte également sur ses propres serveurs certaines actions, comme le démarrage d'un classement, afin de fournir les totaux publics et les métriques produit sans analytique tierce.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. Vos choix</h2><p>Vous pouvez bloquer ou supprimer les cookies et le stockage depuis les réglages du navigateur. Bloquer les cookies nécessaires peut empêcher la connexion, la création de compte ou la préférence de contenu pour adultes de fonctionner. Comme aucun cookie facultatif n'est déposé, RANKMAKER n'affiche pas de bannière de consentement.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. Modifications et contact</h2><p>Cette politique peut évoluer avec les technologies du Service. Pour toute question, écrivez à <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">Dernière mise à jour :</strong> 9 septembre 2026.</p>
<p>Cette Politique de confidentialité explique comment RANKMAKER collecte et utilise des informations lors de votre utilisation de rankmaker.net et de ses services (le « Service »).</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. Informations collectées</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Compte :</strong> nom d'utilisateur, avatar choisi, identifiant stable du fournisseur de connexion sélectionné, adresse e-mail et statut de vérification lorsque le fournisseur les transmet.</li><li><strong class="text-text-primary">Contenu et activité :</strong> modèles, images, commentaires, votes, abonnements, modèles enregistrés, résultats de classement, préférences et choix de notification soumis ou enregistrés.</li><li><strong class="text-text-primary">Mesures produit :</strong> événements tels que le démarrage d'un classement, modèle concerné, date, pays approximatif et, si vous êtes connecté, identifiant de compte. Les mesures des modèles invités contiennent un identifiant local opaque et des dates d'étapes, sans titre, options ni images.</li><li><strong class="text-text-primary">Informations techniques :</strong> données réseau et appareil traitées par nos fournisseurs d'infrastructure pour fournir et sécuriser le Service.</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. Utilisation des informations</h2><ul class="list-disc pl-5 space-y-2"><li>Fournir les comptes, classements, modèles et fonctions communautaires.</li><li>Sécuriser le Service, prévenir les abus et diagnostiquer les pannes.</li><li>Maintenir les compteurs agrégés, comprendre l'usage et améliorer les performances.</li><li>Envoyer les notifications d'activité que vous n'avez pas désactivées.</li></ul><p class="mt-3"><strong class="text-text-primary">E-mails promotionnels.</strong> Les actualités RANKMAKER ne sont envoyées qu'avec votre accord explicite. Cette option est désactivée par défaut, distincte des notifications d'activité et révocable à tout moment dans les Préférences.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Cookies, stockage local et analytique</h2><p>RANKMAKER utilise des cookies internes nécessaires à l'authentification, à la sécurité OAuth et à la préférence de contenu pour adultes, ainsi que le stockage du navigateur pour les fonctions invité et l'historique local. Nous n'utilisons aucun cookie publicitaire ou analytique tiers. Cloudflare Web Analytics fournit des mesures agrégées du trafic et des performances sans déposer de cookies ; Cloudflare déclare ne pas collecter ni utiliser les données personnelles des visiteurs.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. Prestataires et divulgation</h2><p class="mb-3">Nous ne vendons pas les données personnelles et ne les utilisons pas pour la publicité de tiers. Les prestataires suivants interviennent uniquement lorsque le fonctionnement du Service l'exige :</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare :</strong> hébergement, sécurité, base de données et stockage d'objets, traitement d'images, descriptions assistées par IA et analytique web respectueuse de la vie privée.</li><li><strong class="text-text-primary">Google ou GitHub :</strong> le fournisseur choisi vous authentifie et renvoie l'identifiant de compte et les informations d'e-mail décrits ci-dessus.</li><li><strong class="text-text-primary">Resend :</strong> envoi des notifications et e-mails promotionnels consentis.</li><li><strong class="text-text-primary">OpenAI :</strong> modération automatique des images que vous choisissez de téléverser, lorsque cette fonction est activée.</li></ul><p class="mt-3">Nous pouvons aussi divulguer des informations lorsque la loi l'exige ou pour protéger les utilisateurs, le Service ou nos droits.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. Conservation et suppression</h2><p>Les données personnelles sont conservées uniquement le temps nécessaire au Service, aux obligations légales et à la prévention des abus. Vous pouvez supprimer votre compte depuis votre profil. Cela supprime le compte, ses modèles, images téléversées et résultats enregistrés. Les commentaires sont détachés et affichés comme provenant d'un utilisateur supprimé afin de conserver les réponses d'autres personnes. Des mesures agrégées ou désidentifiées peuvent subsister sans compte actif.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. Vos droits</h2><p>Selon votre lieu de résidence, vous pouvez disposer de droits d'accès, de rectification, d'effacement, de limitation, d'opposition, de portabilité et de retrait du consentement. Nous pouvons devoir vérifier votre identité. Vous pouvez également saisir votre autorité locale de protection des données.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. Enfants</h2><p>Le Service ne s'adresse pas aux enfants de moins de 13 ans et nous ne collectons pas sciemment leurs données personnelles.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. Sécurité et traitement international</h2><p>Nous appliquons des mesures techniques et organisationnelles, mais aucun service Internet ne peut garantir une sécurité absolue. Nos prestataires peuvent traiter des données dans d'autres pays selon les garanties qui leur sont applicables.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. Modifications et contact</h2><p>Cette politique peut évoluer avec le Service. Les changements importants seront signalés dans le Service ou par e-mail si nécessaire. Pour exercer vos droits ou poser une question, écrivez à <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`
	},
	de: {
		cookiePolicy: `<p><strong class="text-text-primary">Zuletzt aktualisiert:</strong> 9. September 2026.</p>
<p>RANKMAKER verwendet nur eigene Cookies, die für Anmeldung, Kontosicherheit und die Einstellung für nicht jugendfreie Inhalte erforderlich sind. Wir verwenden keine Werbe- oder Analyse-Cookies von Drittanbietern.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. Verwendete Cookies</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Cookie</th><th class="px-4 py-3 border-b border-border">Zweck</th><th class="px-4 py-3 border-b border-border">Dauer</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">Hält dich angemeldet und identifiziert deine serverseitige Sitzung.</td><td class="px-4 py-3">30 Tage</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">Sichert die Google- oder GitHub-Anmeldeweiterleitung und führt zur angeforderten Seite zurück.</td><td class="px-4 py-3">10 Minuten</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">Überträgt vorübergehend die verifizierten Angaben zum Abschluss der Kontoerstellung.</td><td class="px-4 py-3">15 Minuten</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">Speichert, ob du als nicht jugendfrei markierte Vorlagen anzeigen möchtest.</td><td class="px-4 py-3">1 Jahr</td></tr></tbody></table></div><p class="mt-4">Diese Cookies werden von RANKMAKER gesetzt, verwenden SameSite=Lax und dienen nicht der Werbung. Authentifizierungs-Cookies sind HTTP-only und können nicht von Browser-Skripten gelesen werden.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. Browser-Speicher</h2><p>Der lokale Speicher bewahrt Gastvorlagen, Ranking-Verlauf und -Fortschritt sowie Oberflächen-Caches auf deinem Gerät auf. Sitzungsspeicher dient kurzzeitigen Formular- und Navigationsübergaben. Beim Löschen der Website-Daten verschwinden diese lokalen Kopien; in einem Konto gespeicherte Inhalte bleiben bis zu ihrer Löschung oder der Kontolöschung auf unseren Servern.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. Analyse</h2><p>Cloudflare Web Analytics liefert aggregierte Messungen zu Besuchen, Seitenaufrufen und Leistung. Das Browser-Beacon setzt keine Cookies. Cloudflare erklärt, dass Web Analytics keine personenbezogenen Daten von Besuchern erhebt oder verwendet. RANKMAKER zählt außerdem Produktaktionen wie den Start eines Rankings auf eigenen Servern, damit öffentliche Zähler und Produktmetriken ohne Drittanbieter-Analyse funktionieren.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. Deine Kontrolle</h2><p>Cookies und Browser-Speicher lassen sich in den Browser-Einstellungen blockieren oder löschen. Das Blockieren notwendiger Cookies kann Anmeldung, Kontoerstellung oder die Inhaltspräferenz verhindern. Da wir keine optionalen Cookies setzen, zeigt RANKMAKER kein Cookie-Einwilligungsbanner.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. Änderungen und Kontakt</h2><p>Wir können diese Richtlinie bei Änderungen der eingesetzten Technologien aktualisieren. Fragen bitte an <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">Zuletzt aktualisiert:</strong> 9. September 2026.</p>
<p>Diese Datenschutzerklärung erläutert, wie RANKMAKER bei der Nutzung von rankmaker.net und seinen Diensten (der „Dienst“) Informationen erhebt und verwendet.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. Erhobene Informationen</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Kontodaten:</strong> Benutzername, gewählter Avatar, stabile Kennung des gewählten Anmeldeanbieters sowie E-Mail-Adresse und Verifizierungsstatus, sofern vom Anbieter übermittelt.</li><li><strong class="text-text-primary">Inhalte und Aktivität:</strong> Vorlagen, Bilder, Kommentare, Stimmen, Follows, gespeicherte Vorlagen, Ranking-Ergebnisse, Einstellungen und Benachrichtigungsoptionen.</li><li><strong class="text-text-primary">Produktmessungen:</strong> Ereignisse wie der Start eines Rankings, beteiligte Vorlage, Datum, ungefähres Land und bei Anmeldung die Kontokennung. Messungen zu Gastvorlagen enthalten eine undurchsichtige lokale Kennung und Zeitpunkte, nicht Titel, Optionen oder Bilder.</li><li><strong class="text-text-primary">Technische Informationen:</strong> Netzwerk- und Gerätedaten, die unsere Infrastruktur-Anbieter zur Bereitstellung und Absicherung des Dienstes verarbeiten.</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. Verwendung</h2><ul class="list-disc pl-5 space-y-2"><li>Konten, Rankings, Vorlagen und Community-Funktionen bereitstellen.</li><li>Den Dienst schützen, Missbrauch verhindern und Fehler diagnostizieren.</li><li>Aggregierte Zähler führen, Nutzung verstehen und Leistung verbessern.</li><li>Nicht deaktivierte Aktivitätsbenachrichtigungen senden.</li></ul><p class="mt-3"><strong class="text-text-primary">Marketing-E-Mails.</strong> RANKMAKER-Neuigkeiten senden wir nur nach ausdrücklicher Einwilligung. Die Option ist standardmäßig aus, von Aktivitätsmeldungen getrennt und jederzeit in den Einstellungen widerrufbar.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Cookies, lokaler Speicher und Analyse</h2><p>RANKMAKER nutzt notwendige eigene Cookies für Authentifizierung, OAuth-Sicherheit und die Inhaltspräferenz sowie Browser-Speicher für Gastfunktionen und lokalen Verlauf. Wir verwenden keine Werbe- oder Analyse-Cookies von Drittanbietern. Cloudflare Web Analytics liefert aggregierte Verkehrs- und Leistungsmessungen ohne Cookies; Cloudflare erklärt, keine personenbezogenen Besucherdaten zu erheben oder zu verwenden.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. Dienstleister und Offenlegung</h2><p class="mb-3">Wir verkaufen keine personenbezogenen Daten und nutzen sie nicht für Drittanbieter-Werbung. Folgende Anbieter werden nur soweit für den Betrieb nötig eingesetzt:</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare:</strong> Hosting, Sicherheit, Datenbank- und Objektspeicher, Bildverarbeitung, KI-gestützte Beschreibungen und datenschutzorientierte Webanalyse.</li><li><strong class="text-text-primary">Google oder GitHub:</strong> Der gewählte Anbieter authentifiziert dich und liefert die oben beschriebenen Konto- und E-Mail-Angaben.</li><li><strong class="text-text-primary">Resend:</strong> Versand von Benachrichtigungen und eingewilligten Marketing-E-Mails.</li><li><strong class="text-text-primary">OpenAI:</strong> automatische Moderation freiwillig hochgeladener Bilder, wenn aktiviert.</li></ul><p class="mt-3">Informationen können zudem bei gesetzlicher Pflicht oder zum Schutz von Nutzern, Dienst oder Rechten offengelegt werden.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. Aufbewahrung und Löschung</h2><p>Personenbezogene Daten bleiben nur so lange wie für Dienst, Rechtspflichten und Missbrauchsschutz nötig. Du kannst dein Konto im Profil löschen. Dabei werden Konto, Vorlagen, hochgeladene Bilder und gespeicherte Ergebnisse gelöscht. Kommentare werden abgetrennt und als Inhalt eines gelöschten Nutzers angezeigt, damit Antworten anderer erhalten bleiben. Aggregierte oder de-identifizierte Produktmessungen können ohne aktiven Kontodatensatz verbleiben.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. Deine Rechte</h2><p>Je nach Wohnort kannst du Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch, Datenübertragbarkeit und Widerruf haben. Vor Bearbeitung kann eine Identitätsprüfung nötig sein. Beschwerden sind bei der zuständigen Datenschutzbehörde möglich.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. Kinder</h2><p>Der Dienst richtet sich nicht an Kinder unter 13 Jahren; deren personenbezogene Daten erheben wir nicht wissentlich.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. Sicherheit und internationale Verarbeitung</h2><p>Wir setzen technische und organisatorische Schutzmaßnahmen ein, doch kein Internetdienst kann absolute Sicherheit garantieren. Anbieter können Daten unter den jeweils geltenden Garantien in anderen Ländern verarbeiten.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. Änderungen und Kontakt</h2><p>Diese Richtlinie kann sich mit dem Dienst ändern. Wesentliche Änderungen teilen wir gegebenenfalls im Dienst oder per E-Mail mit. Für Rechteanfragen und Fragen: <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`
	},
	pt: {
		cookiePolicy: `<p><strong class="text-text-primary">Última atualização:</strong> 9 de setembro de 2026.</p>
<p>O RANKMAKER usa somente cookies próprios necessários para login, segurança da conta e preferência de conteúdo adulto. Não usamos cookies de publicidade ou análise de terceiros.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. Cookies que usamos</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Cookie</th><th class="px-4 py-3 border-b border-border">Finalidade</th><th class="px-4 py-3 border-b border-border">Duração</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">Mantém seu login e identifica sua sessão no servidor.</td><td class="px-4 py-3">30 dias</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">Protege o redirecionamento de login do Google ou GitHub e retorna à página solicitada.</td><td class="px-4 py-3">10 minutos</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">Transporta temporariamente os dados verificados necessários para concluir a criação da conta.</td><td class="px-4 py-3">15 minutos</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">Lembra se você escolheu exibir modelos marcados como conteúdo adulto.</td><td class="px-4 py-3">1 ano</td></tr></tbody></table></div><p class="mt-4">Esses cookies são definidos pelo RANKMAKER, usam SameSite=Lax e não servem para publicidade. Os cookies de autenticação são HTTP-only e não podem ser lidos por scripts do navegador.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. Armazenamento do navegador</h2><p>O armazenamento local mantém no dispositivo modelos criados como convidado, histórico e progresso de rankings e caches da interface. O armazenamento de sessão é usado para formulários e transições temporárias. Limpar os dados do site remove essas cópias locais; o conteúdo salvo em uma conta permanece nos servidores até ser excluído ou até a conta ser apagada.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. Análise</h2><p>Usamos o Cloudflare Web Analytics para medições agregadas de visitas, visualizações e desempenho. Seu beacon não define cookies. A Cloudflare declara que o Web Analytics não coleta nem usa dados pessoais dos visitantes. O RANKMAKER também conta em seus próprios servidores ações como iniciar um ranking, mantendo totais públicos e métricas do produto sem análise de terceiros.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. Seus controles</h2><p>Você pode bloquear ou excluir cookies e armazenamento nas configurações do navegador. Bloquear cookies necessários pode impedir login, criação de conta ou a preferência de conteúdo adulto. Como não definimos cookies opcionais, o RANKMAKER não exibe banner de consentimento.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. Alterações e contato</h2><p>Podemos atualizar esta política quando as tecnologias do Serviço mudarem. Dúvidas: <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">Última atualização:</strong> 9 de setembro de 2026.</p>
<p>Esta Política de Privacidade explica como o RANKMAKER coleta e usa informações quando você usa rankmaker.net e seus serviços (o “Serviço”).</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. Informações coletadas</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Conta:</strong> nome de usuário, avatar escolhido, identificador estável do provedor de login selecionado, e-mail e status de verificação quando fornecidos pelo provedor.</li><li><strong class="text-text-primary">Conteúdo e atividade:</strong> modelos, imagens, comentários, votos, seguidores, modelos salvos, resultados de rankings, preferências e opções de notificação enviados ou salvos.</li><li><strong class="text-text-primary">Medições do produto:</strong> eventos como início de ranking, modelo envolvido, data, país aproximado e, quando conectado, identificador da conta. Medições de modelos de convidados contêm um identificador local opaco e datas de marcos, não título, opções ou imagens.</li><li><strong class="text-text-primary">Informações técnicas:</strong> dados de rede e dispositivo processados por provedores de infraestrutura para entregar e proteger o Serviço.</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. Como usamos as informações</h2><ul class="list-disc pl-5 space-y-2"><li>Fornecer contas, rankings, modelos e recursos comunitários.</li><li>Proteger o Serviço, evitar abuso e diagnosticar falhas.</li><li>Manter contagens agregadas, entender o uso e melhorar o desempenho.</li><li>Enviar notificações de atividade que você não desativou.</li></ul><p class="mt-3"><strong class="text-text-primary">E-mails de marketing.</strong> Só enviamos novidades do RANKMAKER com consentimento explícito. A opção fica desativada por padrão, é separada das notificações de atividade e pode ser retirada em Preferências.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Cookies, armazenamento local e análise</h2><p>O RANKMAKER usa cookies próprios necessários para autenticação, segurança OAuth e preferência de conteúdo adulto, além de armazenamento do navegador para recursos de convidado e histórico local. Não usamos cookies de publicidade ou análise de terceiros. O Cloudflare Web Analytics fornece medições agregadas sem cookies; a Cloudflare declara não coletar nem usar dados pessoais dos visitantes.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. Provedores e divulgação</h2><p class="mb-3">Não vendemos dados pessoais nem os usamos para publicidade de terceiros. Usamos apenas quando necessário:</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare:</strong> hospedagem, segurança, banco de dados e armazenamento de objetos, processamento de imagens, descrições assistidas por IA e análise web focada em privacidade.</li><li><strong class="text-text-primary">Google ou GitHub:</strong> o provedor escolhido autentica você e devolve os dados de conta e e-mail descritos acima.</li><li><strong class="text-text-primary">Resend:</strong> entrega de notificações e e-mails de marketing consentidos.</li><li><strong class="text-text-primary">OpenAI:</strong> moderação automatizada das imagens que você decide enviar, quando habilitada.</li></ul><p class="mt-3">Também podemos divulgar informações por obrigação legal ou para proteger usuários, o Serviço ou nossos direitos.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. Retenção e exclusão</h2><p>Mantemos dados pessoais somente pelo tempo necessário para o Serviço, obrigações legais e prevenção de abuso. Você pode excluir a conta no perfil. Isso remove a conta, modelos, imagens enviadas e resultados salvos. Comentários são desvinculados e exibidos como conteúdo de usuário excluído para preservar respostas de outras pessoas. Medições agregadas ou desidentificadas podem permanecer sem um registro de conta ativo.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. Seus direitos</h2><p>Conforme seu local de residência, você pode ter direitos de acesso, correção, exclusão, restrição, oposição, portabilidade ou retirada de consentimento. Podemos precisar verificar sua identidade. Você também pode reclamar à autoridade local de proteção de dados.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. Crianças</h2><p>O Serviço não é direcionado a menores de 13 anos e não coletamos conscientemente seus dados pessoais.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. Segurança e processamento internacional</h2><p>Adotamos medidas técnicas e organizacionais, mas nenhum serviço de Internet garante segurança absoluta. Provedores podem processar dados em outros países conforme as garantias aplicáveis.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. Alterações e contato</h2><p>Podemos atualizar esta política quando o Serviço mudar. Alterações relevantes serão comunicadas no Serviço ou por e-mail quando apropriado. Para exercer direitos ou tirar dúvidas, escreva para <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`
	},
	zh: {
		cookiePolicy: `<p><strong class="text-text-primary">最后更新：</strong>2026 年 9 月 9 日。</p>
<p>RANKMAKER 仅使用登录、账户安全和成人内容偏好所必需的第一方 Cookie。我们不使用第三方广告或分析 Cookie。</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. 我们使用的 Cookie</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Cookie</th><th class="px-4 py-3 border-b border-border">用途</th><th class="px-4 py-3 border-b border-border">期限</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">保持登录并识别服务器端会话。</td><td class="px-4 py-3">30 天</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">保护 Google 或 GitHub 登录跳转，并返回所请求的页面。</td><td class="px-4 py-3">10 分钟</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">临时传递完成账户创建所需的已验证登录信息。</td><td class="px-4 py-3">15 分钟</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">记住是否选择显示标记为成人内容的模板。</td><td class="px-4 py-3">1 年</td></tr></tbody></table></div><p class="mt-4">这些 Cookie 由 RANKMAKER 设置，使用 SameSite=Lax，且不用于广告。身份验证 Cookie 为 HTTP-only，浏览器脚本无法读取。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. 浏览器存储</h2><p>本地存储用于在设备上保存访客创建的模板、排名历史和进度以及界面缓存。会话存储用于短期表单和页面跳转。清除网站数据会删除这些本地副本；保存到账户的内容会保留在服务器上，直到你删除内容或账户。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. 分析</h2><p>我们使用 Cloudflare Web Analytics 获取汇总的访问、页面浏览和性能数据。其浏览器信标不会设置 Cookie。Cloudflare 声明 Web Analytics 不收集或使用访客的个人数据。RANKMAKER 也会在自己的服务器上统计开始排名等产品操作，以便在不使用第三方分析的情况下提供公开计数和产品指标。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. 你的选择</h2><p>你可以在浏览器设置中阻止或删除 Cookie 和浏览器存储。阻止必要 Cookie 可能导致登录、创建账户或成人内容偏好无法工作。由于我们不设置可选 Cookie，RANKMAKER 不显示 Cookie 同意横幅。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. 变更与联系</h2><p>当服务所用技术发生变化时，我们可能更新本政策。如有问题，请发送邮件至 <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>。</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">最后更新：</strong>2026 年 9 月 9 日。</p>
<p>本隐私政策说明你使用 rankmaker.net 及其服务（“服务”）时，RANKMAKER 如何收集和使用信息。</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. 我们收集的信息</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">账户信息：</strong>用户名、所选头像、所选登录提供商的稳定标识符，以及提供商给出的电子邮箱和验证状态。</li><li><strong class="text-text-primary">内容与活动：</strong>你提交或保存的模板、图片、评论、投票、关注、收藏模板、排名结果、偏好和通知选项。</li><li><strong class="text-text-primary">产品测量：</strong>开始排名等事件、相关模板、日期、大致国家，以及登录时的账户标识符。访客模板测量仅包含不透明的本地标识符和里程碑时间，不包含模板标题、选项或图片。</li><li><strong class="text-text-primary">技术信息：</strong>基础设施提供商为交付和保护服务而处理的网络及设备信息。</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. 信息用途</h2><ul class="list-disc pl-5 space-y-2"><li>提供账户、排名、模板和社区功能。</li><li>保护服务、防止滥用并诊断故障。</li><li>维护汇总计数、了解产品使用情况并改善性能。</li><li>发送你未关闭的活动通知。</li></ul><p class="mt-3"><strong class="text-text-primary">营销邮件。</strong>只有在你明确选择加入后，我们才发送 RANKMAKER 动态。该选项默认关闭，与活动通知分开，可随时在偏好设置中撤回。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Cookie、本地存储与分析</h2><p>RANKMAKER 使用身份验证、OAuth 安全和成人内容偏好所必需的第一方 Cookie，并使用浏览器存储提供访客功能和本地历史。我们不使用第三方广告或分析 Cookie。Cloudflare Web Analytics 在不设置 Cookie 的情况下提供汇总流量和性能测量；Cloudflare 声明其不收集或使用访客个人数据。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. 服务提供商与披露</h2><p class="mb-3">我们不出售个人数据，也不将其用于第三方广告。仅在运营服务需要时使用以下提供商：</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare：</strong>托管、安全、数据库和对象存储、图片处理、AI 辅助描述及隐私优先的网站分析。</li><li><strong class="text-text-primary">Google 或 GitHub：</strong>你选择的提供商负责身份验证，并返回上述账户标识符和邮箱信息。</li><li><strong class="text-text-primary">Resend：</strong>发送通知和经同意的营销邮件。</li><li><strong class="text-text-primary">OpenAI：</strong>在启用审核时，对你选择上传的图片进行自动审核。</li></ul><p class="mt-3">法律要求或为保护用户、服务及我们的合法权利时，我们也可能披露信息。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. 保留与删除</h2><p>个人数据仅在提供服务、履行法律义务及防止滥用所需期间保留。你可以在个人资料中删除账户；账户、模板、上传图片和保存的排名结果将被删除。评论会解除关联并显示为已删除用户内容，以保留他人的回复。汇总或去标识化的产品测量可在没有有效账户记录的情况下保留。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. 你的权利</h2><p>根据所在地，你可能有权访问、更正、删除、限制或反对个人数据处理，获取可携带副本或撤回同意。处理请求前我们可能需要验证身份。你也可以向当地数据保护机构投诉。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. 儿童</h2><p>本服务不面向 13 岁以下儿童，我们不会有意收集其个人信息。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. 安全与跨境处理</h2><p>我们采取技术和组织保护措施，但任何互联网服务都无法保证绝对安全。提供商可能依据适用的保护措施在你所在国家以外处理数据。</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. 变更与联系</h2><p>服务变化时我们可能更新本政策。重大变化将在适当时通过服务或邮件通知。行使权利或咨询请发送邮件至 <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>。</p></section>`
	},
	ms: {
		cookiePolicy: `<p><strong class="text-text-primary">Kemas kini terakhir:</strong> 9 September 2026.</p>
<p>RANKMAKER hanya menggunakan kuki pihak pertama yang diperlukan untuk log masuk, keselamatan akaun dan pilihan kandungan matang. Kami tidak menggunakan kuki pengiklanan atau analitik pihak ketiga.</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">1. Kuki yang kami gunakan</h2><div class="overflow-x-auto rounded-xl border border-border"><table class="w-full text-sm text-left"><thead class="bg-surface-elevated text-text-primary font-semibold"><tr><th class="px-4 py-3 border-b border-border">Kuki</th><th class="px-4 py-3 border-b border-border">Tujuan</th><th class="px-4 py-3 border-b border-border">Tempoh</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-4 py-3 font-medium">rm_session</td><td class="px-4 py-3">Mengekalkan log masuk dan mengenal pasti sesi pada pelayan.</td><td class="px-4 py-3">30 hari</td></tr><tr><td class="px-4 py-3 font-medium">rm_oauth_state</td><td class="px-4 py-3">Melindungi ubah hala log masuk Google atau GitHub dan mengembalikan anda ke halaman yang diminta.</td><td class="px-4 py-3">10 minit</td></tr><tr><td class="px-4 py-3 font-medium">rm_signup</td><td class="px-4 py-3">Membawa sementara butiran yang disahkan untuk melengkapkan penciptaan akaun.</td><td class="px-4 py-3">15 minit</td></tr><tr><td class="px-4 py-3 font-medium">rm_mature</td><td class="px-4 py-3">Mengingati pilihan untuk memaparkan templat yang ditandai sebagai kandungan matang.</td><td class="px-4 py-3">1 tahun</td></tr></tbody></table></div><p class="mt-4">Kuki ini ditetapkan oleh RANKMAKER, menggunakan SameSite=Lax dan bukan untuk pengiklanan. Kuki pengesahan ialah HTTP-only dan tidak boleh dibaca oleh skrip pelayar.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">2. Storan pelayar</h2><p>Storan setempat menyimpan templat tetamu, sejarah dan kemajuan ranking serta cache antara muka pada peranti anda. Storan sesi digunakan untuk borang dan peralihan sementara. Memadam data laman membuang salinan setempat ini; kandungan yang disimpan dalam akaun kekal pada pelayan sehingga anda memadamkannya atau memadam akaun.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">3. Analitik</h2><p>Cloudflare Web Analytics memberikan ukuran agregat bagi lawatan, paparan halaman dan prestasi. Suar pelayarnya tidak menetapkan kuki. Cloudflare menyatakan bahawa Web Analytics tidak mengumpul atau menggunakan data peribadi pelawat. RANKMAKER turut mengira tindakan produk seperti memulakan ranking pada pelayannya sendiri supaya jumlah awam dan metrik produk berfungsi tanpa analitik pihak ketiga.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">4. Kawalan anda</h2><p>Anda boleh menyekat atau memadam kuki dan storan melalui tetapan pelayar. Menyekat kuki yang diperlukan mungkin menghalang log masuk, penciptaan akaun atau pilihan kandungan matang. Oleh sebab tiada kuki pilihan, RANKMAKER tidak memaparkan sepanduk persetujuan kuki.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-4">5. Perubahan dan hubungan</h2><p>Kami boleh mengemas kini dasar ini apabila teknologi Perkhidmatan berubah. Untuk pertanyaan, e-mel <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`,
		privacyPolicy: `<p><strong class="text-text-primary">Kemas kini terakhir:</strong> 9 September 2026.</p>
<p>Dasar Privasi ini menerangkan cara RANKMAKER mengumpul dan menggunakan maklumat apabila anda menggunakan rankmaker.net dan perkhidmatannya (“Perkhidmatan”).</p>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">1. Maklumat yang dikumpul</h2><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Akaun:</strong> nama pengguna, avatar pilihan, pengecam stabil daripada penyedia log masuk yang dipilih, serta alamat e-mel dan status pengesahan apabila diberikan.</li><li><strong class="text-text-primary">Kandungan dan aktiviti:</strong> templat, imej, komen, undian, ikutan, templat disimpan, hasil ranking, pilihan dan tetapan pemberitahuan.</li><li><strong class="text-text-primary">Ukuran produk:</strong> peristiwa seperti memulakan ranking, templat terlibat, tarikh, negara anggaran dan pengecam akaun ketika log masuk. Ukuran templat tetamu mengandungi pengecam setempat legap dan masa pencapaian, bukan tajuk, pilihan atau imej.</li><li><strong class="text-text-primary">Maklumat teknikal:</strong> data rangkaian dan peranti yang diproses oleh penyedia infrastruktur untuk menyampaikan dan melindungi Perkhidmatan.</li></ul></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">2. Cara maklumat digunakan</h2><ul class="list-disc pl-5 space-y-2"><li>Menyediakan akaun, ranking, templat dan ciri komuniti.</li><li>Melindungi Perkhidmatan, mencegah penyalahgunaan dan mendiagnosis kegagalan.</li><li>Mengekalkan kiraan agregat, memahami penggunaan dan meningkatkan prestasi.</li><li>Menghantar pemberitahuan aktiviti yang tidak anda matikan.</li></ul><p class="mt-3"><strong class="text-text-primary">E-mel pemasaran.</strong> Berita RANKMAKER hanya dihantar selepas persetujuan jelas. Pilihan ini dimatikan secara lalai, berasingan daripada pemberitahuan aktiviti dan boleh ditarik balik dalam Keutamaan.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">3. Kuki, storan setempat dan analitik</h2><p>RANKMAKER menggunakan kuki pihak pertama yang diperlukan untuk pengesahan, keselamatan OAuth dan pilihan kandungan matang, serta storan pelayar untuk ciri tetamu dan sejarah setempat. Kami tidak menggunakan kuki pengiklanan atau analitik pihak ketiga. Cloudflare Web Analytics menyediakan ukuran trafik dan prestasi agregat tanpa kuki; Cloudflare menyatakan bahawa ia tidak mengumpul atau menggunakan data peribadi pelawat.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">4. Penyedia dan pendedahan</h2><p class="mb-3">Kami tidak menjual data peribadi atau menggunakannya untuk iklan pihak ketiga. Penyedia berikut digunakan hanya apabila diperlukan:</p><ul class="list-disc pl-5 space-y-2"><li><strong class="text-text-primary">Cloudflare:</strong> pengehosan, keselamatan, pangkalan data dan storan objek, pemprosesan imej, penerangan berbantu AI dan analitik web berfokus privasi.</li><li><strong class="text-text-primary">Google atau GitHub:</strong> penyedia pilihan mengesahkan anda dan mengembalikan butiran akaun dan e-mel yang diterangkan di atas.</li><li><strong class="text-text-primary">Resend:</strong> penghantaran pemberitahuan dan e-mel pemasaran yang dipersetujui.</li><li><strong class="text-text-primary">OpenAI:</strong> penyederhanaan automatik imej yang anda pilih untuk muat naik, apabila diaktifkan.</li></ul><p class="mt-3">Maklumat juga boleh didedahkan apabila diwajibkan undang-undang atau untuk melindungi pengguna, Perkhidmatan atau hak kami.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">5. Penyimpanan dan pemadaman</h2><p>Data peribadi disimpan hanya selama diperlukan untuk Perkhidmatan, kewajipan undang-undang dan pencegahan penyalahgunaan. Anda boleh memadam akaun melalui profil. Ini memadam akaun, templat, imej muat naik dan hasil ranking disimpan. Komen dinyahpaut dan dipaparkan sebagai kandungan pengguna dipadam supaya balasan orang lain kekal. Ukuran agregat atau dinyahkenal pasti boleh kekal tanpa rekod akaun aktif.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">6. Hak anda</h2><p>Bergantung pada tempat tinggal, anda mungkin berhak mengakses, membetulkan, memadam, mengehadkan atau membantah pemprosesan, menerima salinan mudah alih atau menarik balik persetujuan. Kami mungkin perlu mengesahkan identiti anda. Anda juga boleh membuat aduan kepada pihak berkuasa perlindungan data tempatan.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">7. Kanak-kanak</h2><p>Perkhidmatan tidak ditujukan kepada kanak-kanak bawah 13 tahun dan kami tidak sengaja mengumpul data peribadi mereka.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">8. Keselamatan dan pemprosesan antarabangsa</h2><p>Kami menggunakan langkah teknikal dan organisasi, tetapi tiada perkhidmatan Internet dapat menjamin keselamatan mutlak. Penyedia boleh memproses data di negara lain mengikut perlindungan yang terpakai.</p></section>
<section><h2 class="text-xl font-semibold text-text-primary mb-3 mt-6">9. Perubahan dan hubungan</h2><p>Kami boleh mengemas kini dasar ini apabila Perkhidmatan berubah. Perubahan penting akan dimaklumkan melalui Perkhidmatan atau e-mel apabila sesuai. Untuk menggunakan hak atau bertanya, e-mel <a href="mailto:rankmaker.net@gmail.com" class="text-primary hover:underline">rankmaker.net@gmail.com</a>.</p></section>`
	}
} as const;
